###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.reference.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

# For more available modules and options, please see the filebeat.reference.yml sample
# configuration file.

#=========================== Filebeat inputs =============================

filebeat.inputs:


- type: log

  enabled: true
  tail_files: true
  paths:
    - /app/support/nginx-1.6.2/logs/access.log

  #exclude_lines: ['^DBG']

  include_lines: ['\d{4}\-\d{2}\-\d{2}']

  #exclude_files: ['.gz$']

  #fields:
  #  level: debug
  #  review: 1


  #multiline.pattern: ^\[

  #multiline.negate: false

  #multiline.match: after


#============================= Filebeat modules ===============================

#filebeat.config.modules:
  #path: ${path.config}/modules.d/*.yml

  #reload.enabled: false

  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

#name:

#tags: ["service-X", "web-tier"]

max_procs: 1

fields:
  env: pro



#============================== Dashboards =====================================
#setup.dashboards.enabled: false

#setup.dashboards.url:

#============================== Kibana =====================================

#setup.kibana:

  #host: "localhost:5601"

  #space.id:

#============================= Elastic Cloud ==================================
#cloud.id:

#cloud.auth:

#================================ Outputs =====================================

#output.console:
  #pretty: true


output.kafka:
  enabled: true
  hosts: ["10.66.204.156:9092","10.80.87.50:9092"]
  topic: "log-nginx-web-pro"
        

#-------------------------- Elasticsearch output ------------------------------
#output.elasticsearch:
  #hosts: ["localhost:9200"]

  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  #hosts: ["localhost:5044"]

  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  #ssl.certificate: "/etc/pki/client/cert.pem"

  #ssl.key: "/etc/pki/client/cert.key"

#================================ Procesors =====================================


queue.spool:
  file:
    path: "${path.data}/spool.dat"
    size: 512MiB
    page_size: 32KiB
  write:
    buffer_size: 10MiB
    flush.timeout: 5s
    flush.events: 1024


# Configure processors to enhance or manipulate events generated by the beat.

processors:
  #- add_host_metadata: ~
  #- add_cloud_metadata: ~
  - add_locale: ~
  - drop_fields:
      fields: ["beat", "offset","prospector","input"]

#================================ Logging =====================================

logging.level: error
logging.to_files: false

#logging.selectors: ["*"]

#============================== Xpack Monitoring ===============================

#xpack.monitoring.enabled: false

#xpack.monitoring.elasticsearch:
